<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="537324" started-at="2022-06-03T03:24:14Z" finished-at="2022-06-03T03:33:12Z">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="537324" started-at="2022-06-03T03:24:14Z" finished-at="2022-06-03T03:33:12Z">
      <class name="tests.CovidTest">
        <test-method status="PASS" signature="Countries01_getCountriesTest()[pri:0, instance:tests.CovidTest@2f217633]" name="Countries01_getCountriesTest" duration-ms="8062" started-at="2022-06-03T03:24:14Z" finished-at="2022-06-03T03:24:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Countries01_getCountriesTest -->
        <test-method status="PASS" signature="Countries02_getWebhookTest()[pri:0, instance:tests.CovidTest@2f217633]" name="Countries02_getWebhookTest" duration-ms="863" started-at="2022-06-03T03:24:22Z" finished-at="2022-06-03T03:24:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Countries02_getWebhookTest -->
        <test-method status="PASS" signature="Countries03_getConfirmedByOneDayTest()[pri:0, instance:tests.CovidTest@2f217633]" name="Countries03_getConfirmedByOneDayTest" duration-ms="526658" started-at="2022-06-03T03:24:23Z" finished-at="2022-06-03T03:33:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Countries03_getConfirmedByOneDayTest -->
        <test-method status="FAIL" signature="Countries04_getConfirmedByCountriesTest()[pri:0, instance:tests.CovidTest@2f217633]" name="Countries04_getConfirmedByCountriesTest" duration-ms="902" started-at="2022-06-03T03:33:10Z" finished-at="2022-06-03T03:33:11Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
Expected: not <0>
     but: was <0>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
Expected: not <0>
     but: was <0>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
at tests.CovidTest.Countries04_getConfirmedByCountriesTest(CovidTest.java:184)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Countries04_getConfirmedByCountriesTest -->
        <test-method status="PASS" signature="Countries05_getStatsTest()[pri:0, instance:tests.CovidTest@2f217633]" name="Countries05_getStatsTest" duration-ms="808" started-at="2022-06-03T03:33:11Z" finished-at="2022-06-03T03:33:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Countries05_getStatsTest -->
      </class> <!-- tests.CovidTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
